site_name: ふるよに ガイド
site_url: https://kafka2306.github.io/furuyoni/
site_description: 桜降る代に決闘を - 初心者向けペアガイド＆攻略情報

theme:
  name: material
  language: ja
  palette:
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/weather-night
        name: 闇夜に還る

  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.follow

  font:
    text: Noto Sans JP
    code: Roboto Mono
    headings: Shippori Mincho


repo_url: https://github.com/kafka2306/furuyoni
repo_name: kafka2306/furuyoni
edit_uri: edit/main/docs/

nav:
  - ホーム: index.md
  - 世界観: lore.md
  - 総合ガイド: rules.md
  - メガミ:
    - 概要: megami/index.md
    - 個別詳細:
      - ユリナ: megami/01_yurina.md
      - サイネ: megami/02_saine.md
      - ヒミカ: megami/03_himika.md
      - トコヨ: megami/04_tokoyo.md
      - オボロ: megami/05_oboro.md
      - ユキヒ: megami/06_yukihi.md
      - シンラ: megami/07_shinra.md
      - ハガネ: megami/08_hagane.md
      - チカゲ: megami/09_chikage.md
      - クルル: megami/10_kururu.md
      - サリヤ: megami/11_sariya.md
      - ライラ: megami/12_laila.md
      - ウツロ: megami/13_utsuro.md
      - ホノカ: megami/14_honoka.md
      - コルヌ: megami/15_korunu.md
      - ヤツハ: megami/16_yatsuha.md
      - ハツミ: megami/17_hatsumi.md
      - ミズキ: megami/18_mizuki.md
      - メグミ: megami/19_megumi.md
      - カナヱ: megami/20_kanawe.md
      - カムヰ: megami/21_kamui.md
      - レンリ: megami/22_renri.md
      - アキナ: megami/23_akina.md
      - シスイ: megami/24_shisui.md
    - カード: megami/cards.md
  - 歴史資料:
    - シーズン1: history/season1.md
    - シーズン2: history/season2.md
    - シーズン3: history/season3.md
    - シーズン4: history/season4.md
    - シーズン5: history/season5.md
    - シーズン6: history/season6.md
    - シーズン7: history/season7.md
    - シーズン8: history/season8.md
    - シーズン9: history/season9.md
    - シーズン10: history/season10.md
  - リソース: resources.md



plugins:
  - search:
      lang: ja
  - glightbox

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/immersive.js

extra_css:
  - assets/custom.css

  - assets/furuyoni_style.css


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kafka2306/furuyoni
